### ISSUE TITLE
API delegering - provider filter

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management-frontend#302]
Start API delegering
I am thinking of a scenario where there are many API providers in the list
In API provider filter I type 'Accenture' and I get 'Brønnøysundregistrene' in a red background
I type 'NAV' and I get 'NAV' in a red background
I am wondering what this red background is used for, since I get it for both positive and negative search result with this.

![Image](https://user-images.githubusercontent.com/117180726/233613422-4bfe6130-3ce6-4c75-b9fc-47f901db5211.gif)

**Comment by Albertlarsen** [comment]
@allinox Guess this will be fixed in #81 ?

**Comment by allinox** [comment]
@anishastphen @jonkjetiloye 

That purple outline is how the design-system displays focus. If you tab your way through the page you will see the same colored outline pop up on other components as well.
I assume that what is happening here is that the component is putting a focus on the first entry in the dropdown list, even if it isn't necessarily a match to your search. I'm not sure if this is intentional or not since we didn't actually make this component - we just use it as-is from the design system.

That said, I'm actually working on a new filter component (which is actually a filter component and not just a multi-select like this one) and once that is done, this select-component will be replaced with that one.

**Comment by allinox** [comment]
@anishastphen 

Is this still an issue with the new filter component?

**Comment by anishastphen** [comment]
@allinox no this is not an issue, closing this
