### ISSUE TITLE
Sette opp ny route til Enkeltrettigheter

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#391]
### Description

Denne oppgaven handler om å forberede routing til Enkeltrettigheter.
Den er todelt:

- Lag ny enum i Router-paths for bruk til Enkeltrettigheter og omdøp den allerede eksisterende enumen til å infikere dens bruk i ApiDelegering (Forslag: ApiDelegationRoute)
- Undersøk om det er gunstig å ha flere enn én router (en per hovedfeature). Hvis det er det, sett opp for ulike på Api-delegering og Enkeltrettigheter. (Obs: Test antall renders som skjer or routing-element)

![image](https://github.com/Altinn/altinn-access-management-frontend/assets/22012997/d8cc8622-65a8-4c85-ad8c-0f1b425e1f37)

### Design review
Sjekk at alle flytene og navigeringsknapper fungerer som de skal

**Comment by Albertlarsen** [comment]
In a typical React application, it is generally recommended to have a single Router component that handles the routing for the entire application. This is because the Router is responsible for managing the application's URL and mapping it to different components or views.

Having multiple Router components can lead to conflicts and unexpected behavior, as each Router maintains its own routing state. It can result in difficulties in managing nested routes, maintaining consistent URL synchronization, and coordinating navigation across different parts of the application.

However, there might be specific scenarios where you may have a valid use case for multiple routers. For example, if you have a large application with distinct sections that are completely separate from each other and don't need to share routing information, you could potentially use multiple routers.

But in most cases, a single top-level Router, such as the BrowserRouter or HashRouter from React Router, is sufficient to handle routing for the entire application. It provides a centralized and consistent way to manage navigation and URL changes across different components and views.

Remember to design your application's routing structure carefully and consider the overall architecture to determine the appropriate usage of routers.

**Comment by Randiabs** [comment]
sjekket ok
