### ISSUE TITLE
API delegering - virksomhet søk gir ikke noe treff

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management-frontend#495]
Gå til API delegering side
Start API delegering og søk etter en org - gir ikke noe treff
Den pleide å funke i går, nå feiler det i alle AT miljøer

<img width="558" alt="image" src="https://github.com/Altinn/altinn-access-management/assets/117180726/b8823967-eb31-4e32-9af4-1ae07443053f">

**Comment by Albertlarsen** [comment]
Please create these issues in altinn-access-management-frontend repo instead so we don't have to transfer it before referring it in our PRs

**Comment by Albertlarsen** [comment]
Testet akkurat fiksen som ble pushet på dette @anishastphen, nå skal det funke igjen i alle andre miljøer enn AT23 😁

**Comment by allinox** [comment]
@anishastphen 
I've added a fix that works in AT23 as well. So that you can search for orgs.

However, since the mock is now active in this environment, you can only search for orgs that are present in the mock data.
To this end I've added 910510789 (VIKESÅ OG ÅLVUNDFJORD) and 991825827 (Digitaliseringsdirektoratet) to the registry mock data so that these are now available for search.
But delegation to them will unfortunately fail.

If there is a certain user (with org) that you usually use for testing and an org you usually use for delegation, you can send me their info (with partyid's) and I can add them to the full flow of the mock data.
Otherwise, the mocking will only be a temporary thing anyway, so maybe it's tolerable that just AT23 will have some failing tests for now.

**Comment by anishastphen** [comment]
fix works in AT22 and AT24, fails only in AT23
so will close the issue for now and will check in AT23 once its available
