### ISSUE TITLE
Move all Altinn 3 related tests in altinn-access-management-frontend repo in Github

### ISSUE THREAD

**Issue by acn-Sneha** [Altinn/altinn-access-management-frontend#708]
- [x] Move all Altinn 3 related which are API-delegering, IdPorten test in altinn-access-management-frontend repo 
- [x] Configure github action so all tests will start running after every deploy

**Comment by andreasisnes** [comment]
For running the E2E cypress tests from GitHub actions the runner needs to be able to connect to endpoints at{21-24}.altinn.cloud. for the time being, these endpoints are not opened on the internet, Hence, the Github action will fail. This issue is blocked until the endpoints are opened or we have custom self-hosted github runner.

**Comment by acn-Sneha** [comment]
Closing this task since we have got access running cypress e2e tests from github action and @andreasisnes has configured it to run from github action for which other tasks are created which can be followed.
